#!/bin/bash
# Text Only

/home/pi/slideFix
echo "Please Enter The URL of Today's Slide"
read SLIDE
sed -i "s#https://.*#$SLIDE#g" /home/pi/.xsession
echo "Slide Updated. Rebooting."
sleep 3s
sudo shutdown -r now
