#! /bin/sh

### BEGIN INIT INFO
# Provides:          my-service-name
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: your description here
### END INIT INFO


do_start () {
    /usr/bin/fbi -T 1 -noverbose -a /etc/Green-Wall.png    
    exit 0
}

case "$1" in
  start)
    do_start
    ;;
  restart|reload|force-reload)
    echo "You can't do that" >&2
    exit 3No-op
    ;;
  stop)
    # Nothing here. Move on.
    ;;
  status)
    exit 0
    ;;
  *)
    echo "Script to show splash screen " >&2
    exit 3
    ;;
esac

:

